<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="description" content="SmartRadio - Giải pháp truyền thanh thông minh">
    <link href="../module/Homepage/assets/images/favicon/favicon.png" rel="icon">
    <title>SmartRadio - Giải pháp truyền thanh thông minh</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=Roboto:wght@400;700&display=swap">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
    <link rel="stylesheet" href="../module/Homepage/assets/css/libraries.css">
    <link rel="stylesheet" href="../module/Homepage/assets/css/style.css">
</head>

<body>
    <div class="wrapper">
        <div class="preloader">
            <div class="loading">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <!-- /.preloader -->

        <!-- =========================
        Header
    =========================== -->
        <header class="header header-transparent">
            <nav class="navbar navbar-expand-lg sticky-navbar">
                <div class="container">
                    <a class="navbar-brand" href="index.html">
                        <img src="../module/Homepage/assets/images/logo/logo-light.png" class="logo-light" alt="logo">
                        <img src="../module/Homepage/assets/images/logo/logo-dark.png" class="logo-dark" alt="logo">
                    </a>
                    <button class="navbar-toggler" type="button">
            <span class="menu-lines"><span></span></span>
          </button>
                    <div class="collapse navbar-collapse" id="mainNavigation">
                        <ul class="navbar-nav ml-auto">
                            <!-- /.nav-item -->
                            <li class="nav__item has-dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav__item-link active">Trang chủ</a>
                                <ul class="dropdown-menu">
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Giới thiệu</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Năng lực</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Đội ngũ</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Chứng nhận</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Giá sản phẩm</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Câu hỏi thường gặp</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">Việc làm</a>
                                    </li>
                                    <!-- /.nav-item -->
                                </ul>
                                <!-- /.dropdown-menu -->
                            </li>
                            <!-- /.nav-item -->
                            <li class="nav__item has-dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav__item-link">Giải pháp</a>
                                <ul class="dropdown-menu wide-dropdown-menu">
                                    <li class="nav__item">
                                        <div class="row mx-0">
                                            <div class="col-sm-6 dropdown-menu-col">
                                                <a href="#" class="nav__item-link dropdown-menu-title">Truyền thanh cơ sở</a>
                                                <ul class="nav flex-column">
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">IT
                              Management</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">Cyber
                              Security</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">Cloud
                              Computing</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">IT
                              Consulting</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">Software
                              Dev</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="it-solutions-single.html">IT Support</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                </ul>
                                            </div>
                                            <!-- /.col-sm-6 -->
                                            <div class="col-sm-6 dropdown-menu-col">
                                                <a href="industries.html" class="nav__item-link dropdown-menu-title">Truyền thanh thông minh</a>
                                                <ul class="nav flex-column">
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Education,
                              Non-Profit</a></li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Accounting,
                              Finance</a></li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Government &
                              Public</a></li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Energy
                              &
                              Utilities</a></li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Legal,
                              Law
                              Firms</a></li>
                                                    <!-- /.nav-item -->
                                                    <li class="nav__item"><a class="nav__item-link" href="industries-single-industry.html">Manufacturing</a>
                                                    </li>
                                                    <!-- /.nav-item -->
                                                </ul>
                                            </div>
                                            <!-- /.col-sm-6 -->
                                        </div>
                                        <!-- /.row -->
                                    </li>
                                    <!-- /.nav-item -->
                                </ul>
                                <!-- /.dropdown-menu -->
                            </li>
                            <!-- /.nav-item -->
                            <li class="nav__item has-dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav__item-link">Sản phẩm</a>
                                <ul class="dropdown-menu">
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">IP Audio Box</a>
                                    </li>
                                    <!-- /.nav-item -->
                                    <li class="nav__item">
                                        <a href="#" class="nav__item-link">FM Audio Box</a>
                                    </li>
                                    <!-- /.nav-item -->
                                </ul>
                                <!-- /.dropdown-menu -->
                            </li>
                            <!-- /.nav-item -->
                            <li class="nav__item has-dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav__item-link">Tin tức - Sự kiện</a>
                                <ul class="dropdown-menu">
                                    <li class="nav__item">
                                        <a href="blog.html" class="nav__item-link">Tin khuyến mãi</a>
                                    </li>
                                    <li class="nav__item">
                                        <a href="blog.html" class="nav__item-link">Tin sản phẩm</a>
                                    </li>
                                </ul>
                                <!-- /.dropdown-menu -->
                            </li>
                            <!-- /.nav-item -->
                            <li class="nav__item has-dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav__item-link">Cơ sở pháp lý</a>
                                <!-- /.dropdown-menu -->
                            </li>
                            <!-- /.nav-item -->
                            <li class="nav__item">
                                <a href="contact-us.html" class="nav__item-link">Liên hệ</a>
                            </li>
                            <!-- /.nav-item -->
                        </ul>
                        <!-- /.navbar-nav -->
                        <button class="close-mobile-menu d-block d-lg-none"><i class="fas fa-times"></i></button>
                    </div>
                    <!-- /.navbar-collapse -->
                    <div class="d-flex align-items-center">
                        <a href="#" class="action__btn action__btn-search ml-30"><i class="icon-search"></i></a>
                    </div>
                </div>
                <!-- /.container -->
            </nav>
            <!-- /.navabr -->
        </header>
        <!-- /.Header -->

        <!-- ============================
        Slider
    ============================== -->
        <section class="slider slider-layout2">
            <div class="slick-carousel carousel-arrows-light carousel-dots-light m-slides-0" data-slick='{"slidesToShow": 1, "arrows": true, "dots": true, "speed": 700,"fade": true,"cssEase": "linear"}'>
                <div class="slide-item align-v-h bg-overlay bg-overlay-gradient">
                    <div class="bg-img"><img src="../module/Homepage/assets/images/sliders/4.jpg" alt="slide img"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-7">
                                <div class="slide__content">
                                    <h2 class="slide__title">SmartRadio Giải pháp truyền thanh thông minh!</h2>
                                    <p class="slide__desc">We are experienced professionals who understand that It services is changing, and are true partners who care about your success.</p>
                                    <div class="d-flex flex-wrap align-items-center">
                                        <a href="#" class="btn btn__white mr-30">
                                            <i class="icon-arrow-right"></i>
                                            <span>Sản phẩm</span>
                                        </a>
                                        <a class="video__btn video__btn-white popup-video" href="https://www.youtube.com/watch?v=-smlfBAVFuM">
                                            <div class="video__player">
                                                <span class="video__player-animation"></span>
                                                <span class="video__player-animation video__player-animation-2"></span>
                                                <i class="fa fa-play"></i>
                                            </div>
                                            <span class="video__btn-title color-white">Xem video!</span>
                                        </a>
                                    </div>
                                </div>
                                <!-- /.slide-content -->
                            </div>
                            <!-- /.col-xl-7 -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.container -->
                </div>
                <!-- /.slide-item -->
                <div class="slide-item align-v-h bg-overlay bg-overlay-gradient">
                    <div class="bg-img"><img src="../module/Homepage/assets/images/sliders/3.jpg" alt="slide img"></div>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-7">
                                <div class="slide__content">
                                    <h2 class="slide__title">Các ưu điểm truyền thanh thông minh!</h2>
                                    <p class="slide__desc">We are experienced professionals who understand that It services is changing, and are true partners who care about your success.</p>
                                    <div class="d-flex flex-wrap align-items-center">
                                        <a href="#" class="btn btn__white mr-30">
                                            <i class="icon-arrow-right"></i>
                                            <span>Sản phẩm</span>
                                        </a>
                                        <a class="video__btn video__btn-white popup-video" href="https://www.youtube.com/watch?v=-smlfBAVFuM">
                                            <div class="video__player">
                                                <span class="video__player-animation"></span>
                                                <span class="video__player-animation video__player-animation-2"></span>
                                                <i class="fa fa-play"></i>
                                            </div>
                                            <span class="video__btn-title color-white">Xem video!</span>
                                        </a>
                                    </div>
                                </div>
                                <!-- /.slide-content -->
                            </div>
                            <!-- /.col-xl-7 -->
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.container -->
                </div>
                <!-- /.slide-item -->
            </div>
            <!-- /.carousel -->
        </section>
        <!-- /.slider -->

        <!-- ======================
    Features Layout 4
    ========================= -->
        <section class="features-layout4 bg-overlay bg-overlay-primary bg-parallax pt-0 pb-50">
            <div class="bg-img"><img src="../module/Homepage/assets/images/banners/4.jpg" alt="background"></div>
            <div class="container">
                <div class="row">
                    <!-- Feature item #1 -->
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <div class="feature-item">
                            <div class="feature__icon">
                                <i class="icon-statistic"></i>
                            </div>
                            <h4 class="feature__title">Hạ tầng 4G tiên tiến nhất</h4>
                            <a href="#" class="btn__link">
                                <i class="icon-arrow-right icon-outlined"></i>
                                <span>Xem thêm</span>
                            </a>
                        </div>
                        <!-- /.feature-item -->
                    </div>
                    <!-- /.col-lg-3 -->
                    <!-- Feature item #2 -->
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <div class="feature-item">
                            <div class="feature__icon">
                                <i class="icon-software"></i>
                            </div>
                            <h4 class="feature__title">Độ phủ sóng phạm vi rộng khắp</h4>
                            <a href="#" class="btn__link">
                                <i class="icon-arrow-right icon-outlined"></i>
                                <span>Xem thêm</span>
                            </a>
                        </div>
                        <!-- /.feature-item -->
                    </div>
                    <!-- /.col-lg-3 -->
                    <!-- Feature item #3 -->
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <div class="feature-item">
                            <div class="feature__icon">
                                <i class="icon-website"></i>
                            </div>
                            <h4 class="feature__title">Chất lượng âm thanh cao</h4>
                            <a href="#" class="btn__link">
                                <i class="icon-arrow-right icon-outlined"></i>
                                <span>Xem thêm</span>
                            </a>
                        </div>
                        <!-- /.feature-item -->
                    </div>
                    <!-- /.col-lg-3 -->
                    <!-- Feature item #4 -->
                    <div class="col-sm-6 col-md-6 col-lg-3">
                        <div class="feature-item">
                            <div class="feature__icon">
                                <i class="icon-management"></i>
                            </div>
                            <h4 class="feature__title">Không bị ảnh hưởng thời tiết</h4>
                            <a href="#" class="btn__link">
                                <i class="icon-arrow-right icon-outlined"></i>
                                <span>Xem thêm</span>
                            </a>
                        </div>
                        <!-- /.feature-item -->
                    </div>
                    <!-- /.col-lg-3 -->
                </div>
                <!-- /.row -->
                <div class="row mt-30">
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <blockquote class="blockquote">
                            <h4 class="blockquote__title">Phần mềm truyền thanh lõi (Core Truyền thanh) : được thiết với kiến trúc mođun, các chức và mođun có độ tùy biến theo quy trình vận hành từng đài.
                            </h4>
                            <span class="blockquote__author">Smart Radio</span>
                        </blockquote>
                    </div>
                    <!-- /.col-lg-6 -->
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <div class="slick-carousel clients-light" data-slick='{"slidesToShow": 4, "arrows": false, "dots": false, "autoplay": true,"autoplaySpeed": 2000, "infinite": true, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 3}}, {"breakpoint": 767, "settings": {"slidesToShow": 3}}, {"breakpoint": 480, "settings": {"slidesToShow": 2}}]}'>
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/1.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/1.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/2.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/2.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/3.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/3.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/4.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/4.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/5.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/5.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/6.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/6.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/7.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/7.png" alt="client">
                            </div>
                            <!-- /.client -->
                        </div>
                        <!-- /.carousel -->
                        <span class="blockquote__author">Khách hàng</span>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.Features Layout 4 -->

        <!-- ========================
        Services Layout 1
    =========================== -->
        <section class="services-layout1 services-carousel pb-100">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
                        <div class="heading text-center mb-50">
                            <h2 class="heading__subtitle">Smart IP Radio - Truyền thanh thông minh</h2>
                            <h3 class="heading__title">Giải pháp & Sản phẩm </h3>
                        </div>
                        <!-- /.heading -->
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="slick-carousel" data-slick='{"slidesToShow": 3, "slidesToScroll": 3, "arrows": false, "dots": false, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 2}}, {"breakpoint": 767, "settings": {"slidesToShow": 2}}, {"breakpoint": 480, "settings": {"slidesToShow": 1}}]}'>
                            <!-- service item #1 -->
                            <div class="service-item">
                                <div class="service__icon">
                                    <i class="icon-server"></i>
                                </div>
                                <!-- /.service__icon -->
                                <h4 class="service__title">Truyền thanh IP <br> SmartRadio</h4>
                                <div class="service__content">
                                    <p class="service__desc">IT management service that manages and oversees the IT of organization responsible for network and operations which includes data communication.
                                    </p>
                                    <a href="it-solutions-single.html" class="btn btn__primary">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.service-content -->
                            </div>
                            <!-- /.service-item -->
                            <!-- service item #2 -->
                            <div class="service-item">
                                <div class="service__icon">
                                    <i class="icon-cloud"></i>
                                </div>
                                <!-- /.service__icon -->
                                <h4 class="service__title">Ứng dụng dân cư<br> SmartRadio App</h4>
                                <div class="service__content">
                                    <p class="service__desc">Drive your business and manage risk with a global industry leader in cybersecurity, cloud, and managed security services and extend your team with leading experts.</p>
                                    <a href="it-solutions-single.html" class="btn btn__primary">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.service-content -->
                            </div>
                            <!-- /.service-item -->
                            <!-- service item #3 -->
                            <div class="service-item">
                                <div class="service__icon">
                                    <i class="icon-hosting"></i>
                                </div>
                                <!-- /.service__icon -->
                                <h4 class="service__title">Giải pháp bảo mật<br>Multi-layer Security </h4>
                                <div class="service__content">
                                    <p class="service__desc">Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management .
                                    </p>
                                    <a href="it-solutions-single.html" class="btn btn__primary">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.service-content -->
                            </div>
                            <!-- /.service-item -->

                        </div>
                        <!-- /.carousel -->
                    </div>
                    <!-- /.col-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12 text-center">
                        <p class="text__link mt-20 mb-0">Chúng tôi luôn nỗ lực để lấy niềm tin khách hàng
                            <a href="industries.html" class="btn btn__secondary btn__link mx-1">
                                <span>Xem thêm các giải pháp</span> <i class="icon-arrow-right icon-outlined"></i>
                            </a>
                        </p>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
            </div>
            <!-- /.container -->
        </section>
        <!-- /.Services Layout 1 -->

        <!-- =========================
       Banner layout 2
      =========================== -->
        <section class="banner-layout2 py-0 bg-secondary">
            <div class="container-fluid px-0">
                <div class="row row-no-gutter align-items-center">
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <div class="banner-text inner-padding">
                            <div class="heading-layout2 mb-60">
                                <h2 class="heading__subtitle">SmartRadio Application.</h2>
                                <h3 class="heading__title color-white mb-30">Ứng dụng Dân Cư!</h3>
                                <p class="heading__desc">Provide users with appropriate view and access permissions to requests, problems, changes, contracts, assets, solutions, and reports with our experienced professionals.
                                </p>
                            </div>
                            <!-- /.heading -->
                            <div class="row fancybox-light">
                                <div class="col-sm-4">
                                    <!-- fancybox item #1 -->
                                    <div class="fancybox-item">
                                        <a href="#" class="btn btn__white btn__download mb-20">
                                            <i class="fab fa-apple"></i>
                                            <span>App Store</span>
                                        </a>
                                        <!-- /.fancybox__icon -->
                                        <div class="fancybox__content">
                                            <h4 class="fancybox__title">Download App Store</h4>

                                        </div>
                                        <!-- /.fancybox-content -->
                                    </div>
                                    <!-- /.fancybox-item -->
                                </div>
                                <!-- /.col-lg-3 -->
                                <div class="col-sm-4">
                                    <!-- fancybox item #2 -->
                                    <div class="fancybox-item">
                                        <a href="#" class="btn btn__white btn__download mb-20">
                                            <i class="fab fa-google-play"></i>
                                            <span>Google Play</span>
                                        </a>
                                        <!-- /.fancybox__icon -->
                                        <div class="fancybox__content">
                                            <h4 class="fancybox__title">Download Google Play</h4>

                                        </div>
                                        <!-- /.fancybox-content -->
                                    </div>
                                    <!-- /.fancybox-item -->
                                </div>
                                <!-- /.col-lg-3 -->
                            </div>
                            <!-- /.row -->
                        </div>
                    </div>
                    <!-- /.col-xl-6 -->
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <div class="banner-img">
                            <img src="../module/Homepage/assets/images/banners/3.jpg" alt="banner" class="w-100">
                        </div>
                    </div>
                    <!-- /.col-xl-6 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.Banner layout 2 -->
        <!-- =========================== 
      portfolio layout 2
    ============================= -->
        <section class="portfolio-layout2 portfolio-layout2-carousel pb-50">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 text-center">
                        <div class="heading mb-50">
                            <h2 class="heading__subtitle color-body">Các cam kết về pháp lý</h2>
                            <h3 class="heading__title">Cơ sở pháp lý</h3>
                        </div>
                        <!-- /heading -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="slick-carousel" data-slick='{"slidesToShow": 3, "slidesToScroll": 3, "arrows": false, "dots": true, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 2}}, {"breakpoint": 767, "settings": {"slidesToShow": 2}}, {"breakpoint": 480, "settings": {"slidesToShow": 1}}]}'>
                            <!-- portfolio item #1 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/1.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/1.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Giấy phép của cục SHTT</a></h4>
                                    <p class="portfolio__desc">Hệ thống phần mềm đã được Cục Sở Hữu Trí Tuệ cấp phép, Giấy chứng nhận đăng ký quyền tác giả của cục bản quyền tác giả </p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->

                            </div>
                            <!-- /.portfolio-item -->
                            <!-- portfolio item #2 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/2.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/2.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Phần mềm truyền thanh lõi </a></h4>
                                    <p class="portfolio__desc">Phần mềm truyền thanh lõi (Core Truyền thanh) : được thiết với kiến trúc mođun, các chức và mođun có độ tùy biến theo quy trình vận hành từng đài.
                                    </p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->
                            </div>
                            <!-- /.portfolio-item -->
                            <!-- portfolio item #3 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/3.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/3.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Chứng nhận ISO 9001/2015</a></h4>
                                    <p class="portfolio__desc">Phần cứng được chứng nhận về ISO 9001/2015, các giấy tờ về hợp chuận hợp quy của Bộ thông tin truyền thông ban hành
                                    </p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->
                            </div>
                            <!-- /.portfolio-item -->
                            <!-- portfolio item #4 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/4.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/4.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Chứng nhận bảo mật</a></h4>
                                    <p class="portfolio__desc">Hệ thống được các tổ chức bảo mật (An Ninh Mạng) kiểm định về độ An toàn và bảo mật</p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->
                            </div>
                            <!-- /.portfolio-item -->
                            <!-- portfolio item #1 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/1.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/1.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Giấy phép của cục SHTT</a></h4>
                                    <p class="portfolio__desc">Hệ thống phần mềm đã được Cục Sở Hữu Trí Tuệ cấp phép, Giấy chứng nhận đăng ký quyền tác giả của cục bản quyền tác giả</p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->

                            </div>
                            <!-- /.portfolio-item -->
                            <!-- portfolio item #2 -->
                            <div class="portfolio-item">
                                <div class="portfolio__img">
                                    <a href="case-studies-single.html"><img src="../module/Homepage/assets/images/portfolio/modern/2.jpg" alt="portfolio img"></a>
                                </div>
                                <!-- /.portfolio-img -->
                                <div class="portfolio__icon">
                                    <img src="../module/Homepage/assets/images/icons/2.png" alt="icon">
                                </div>
                                <!-- /.portfolio__icon -->
                                <div class="portfolio__content">
                                    <h4 class="portfolio__title"><a href="#">Phần mềm truyền thanh lõi </a></h4>
                                    <p class="portfolio__desc">Phần mềm truyền thanh lõi (Core Truyền thanh) : được thiết với kiến trúc mođun, các chức và mođun có độ tùy biến theo quy trình vận hành từng đài.
                                    </p>
                                    <a href="case-studies-single.html" class="btn btn__secondary btn__link">
                                        <span>Xem thêm</span>
                                        <i class="icon-arrow-right"></i>
                                    </a>
                                </div>
                                <!-- /.portfolio-content -->
                            </div>
                            <!-- /.portfolio-item -->

                        </div>
                        <!-- /.carousel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-12 text-center">
                        <p class="text__link mb-0">Chúng tôi luôn nỗ lực để lấy niềm tin khách hàng.
                            <a href="industries.html" class="btn btn__secondary btn__link mx-1">
                                <span>Xem thêm các giải pháp</span> <i class="icon-arrow-right icon-outlined"></i>
                            </a>
                        </p>
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.portfolio layout 2 -->

        <!-- ========================= 
      Testimonials layout 2
      =========================  -->
        <section class="testimonials testimonials-layout2 testimonials-has-top-img pb-70">
            <div class="bg-img"><img src="../module/Homepage/assets/images/backgrounds/5.png" alt="backgrounds"></div>
            <img src="../module/Homepage/assets/images/testimonials/testimonials-group.png" alt="testimonials" class="testimonials-top-img">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-6 offset-xl-2">
                        <div class="heading mb-60">
                            <h2 class="heading__subtitle">Hệ thống SmartRadio được đánh giá cao</h2>
                            <h3 class="heading__title">Đã triển khai hơn 25 Tỉnh/ Thành phố từ Bắc-Trung-Nam, vùng sâu vùng xa, miền núi, miền biển </h3>
                        </div>
                        <!-- /.heading -->
                    </div>
                    <!-- /.col-xl-6 -->
                    <div class="col-12">
                        <div class="slick-carousel" data-slick='{"slidesToShow": 3,"slidesToScroll": 3, "arrows": false, "dots": true, "autoplay": false, "infinite": false, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 2}}, {"breakpoint": 767, "settings": {"slidesToShow": 2}}, {"breakpoint": 480, "settings": {"slidesToShow": 2}}]}'>
                            <!-- Testimonial item #1 -->
                            <div class="testimonial-item">
                                <div class="testimonial__rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                </div>
                                <h3 class="testimonial__title">Giải pháp truyền thanh thông minh là một mảnh ghép quan trọng góp phần xây dựng thành phố thông minh tại Việt Nam.
                                </h3>
                                <div class="testimonial__meta d-flex align-items-center">
                                    <div class="testimonial__thmb mr-20">
                                        <img src="../module/Homepage/assets/images/testimonials/thumbs/1.png" alt="author thumb">
                                    </div>
                                    <!-- /.testimonial-thumb -->
                                    <div>
                                        <h4 class="testimonial__meta-title">Nguyễn Sơn</h4>
                                        <p class="testimonial__meta-desc">Kỹ sư VNPT-IT</p>
                                    </div>
                                </div>
                                <!-- /.testimonial-meta -->
                            </div>
                            <!-- /. testimonial-item -->
                            <!-- Testimonial item #2 -->
                            <div class="testimonial-item">
                                <div class="testimonial__rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                </div>
                                <h3 class="testimonial__title">SmartRadio quá tuyệt trong việc thay thế và khắc phục hoàn toàn những nhược điểm của giải pháp truyền thông có dây hay AM/ FM truyền thống.
                                </h3>
                                <div class="testimonial__meta d-flex align-items-center">
                                    <div class="testimonial__thmb mr-20">
                                        <img src="../module/Homepage/assets/images/testimonials/thumbs/2.png" alt="author thumb">
                                    </div>
                                    <!-- /.testimonial-thumb -->
                                    <div>
                                        <h4 class="testimonial__meta-title">Xuân Hiệp</h4>
                                        <p class="testimonial__meta-desc">Chuyên viên IT</p>
                                    </div>
                                </div>
                                <!-- /.testimonial-meta -->
                            </div>
                            <!-- /. testimonial-item -->
                            <!-- Testimonial item #3 -->
                            <div class="testimonial-item">
                                <div class="testimonial__rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                </div>
                                <h3 class="testimonial__title">SmartRadio có thể giao tiếp các công nghệ mới (Trí tuệ nhân tạo) : nhận dang và sử lý tiếng (Chuyển đổi văn bảng sang âm thanh)

                                </h3>
                                <div class="testimonial__meta d-flex align-items-center">
                                    <div class="testimonial__thmb mr-20">
                                        <img src="../module/Homepage/assets/images/testimonials/thumbs/3.png" alt="author thumb">
                                    </div>
                                    <!-- /.testimonial-thumb -->
                                    <div>
                                        <h4 class="testimonial__meta-title">Thu Hiền</h4>
                                        <p class="testimonial__meta-desc">IT Manager</p>
                                    </div>
                                </div>
                                <!-- /.testimonial-meta -->
                            </div>
                            <!-- /. testimonial-item -->
                            <!-- Testimonial item #4 -->
                            <div class="testimonial-item">
                                <div class="testimonial__rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                </div>
                                <h3 class="testimonial__title">SmartRadio là ứng dụng rất dễ vận hành, quản lý với chi phí đầu tư thấp.
                                </h3>
                                <div class="testimonial__meta d-flex align-items-center">
                                    <div class="testimonial__thmb mr-20">
                                        <img src="../module/Homepage/assets/images/testimonials/thumbs/4.png" alt="author thumb">
                                    </div>
                                    <!-- /.testimonial-thumb -->
                                    <div>
                                        <h4 class="testimonial__meta-title">Martin Trần</h4>
                                        <p class="testimonial__meta-desc">Sacombank</p>
                                    </div>
                                </div>
                                <!-- /.testimonial-meta -->
                            </div>
                            <!-- /. testimonial-item -->
                        </div>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.testimonials 2 -->

        <!-- =====================
           Clients
    ======================== -->
        <section class="clients border-top border-top pt-50 pb-50">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-12">
                        <div class="slick-carousel" data-slick='{"slidesToShow": 6, "arrows": false, "dots": false, "autoplay": true,"autoplaySpeed": 2000, "infinite": true, "responsive": [ {"breakpoint": 992, "settings": {"slidesToShow": 4}}, {"breakpoint": 767, "settings": {"slidesToShow": 3}}, {"breakpoint": 480, "settings": {"slidesToShow": 2}}]}'>
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/1.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/1.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/2.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/2.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/3.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/3.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/4.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/4.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/5.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/5.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/6.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/6.png" alt="client">
                            </div>
                            <!-- /.client -->
                            <div class="client">
                                <img src="../module/Homepage/assets/images/clients/7.png" alt="client">
                                <img src="../module/Homepage/assets/images/clients/7.png" alt="client">
                            </div>
                            <!-- /.client -->
                        </div>
                        <!-- /.carousel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.clients -->

        <!-- =========================
       Banner layout 1
      =========================== -->
        <section id="banner" class="banner-layout1 pt-130 bg-overlay bg-overlay-primary">
            <div class="bg-img"><img src="../module/Homepage/assets/images/banners/4.jpg" alt="background"></div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-5 d-flex flex-column justify-content-between">
                        <div>
                            <div class="heading heading-light mb-50">
                                <h2 class="heading__subtitle">Ứng dụng công nghệ IoT quản lý từng thiết bị phát thanh, đảm bảo thông tin luôn được thông suốt.</h2>
                                <h3 class="heading__title mb-30">Cùng tìm hiểu về Hệ thống truyền thanh thông minh 4.0 SmartRadio!
                                </h3>
                                <p class="heading__desc">Phát thanh không dây trên nền tảng data 3G/ 4G/ Internet, đảm bảo mỹ quan đô thị. Ứng dụng công nghệ IoT quản lý từng thiết bị phát thanh, đảm bảo thông tin luôn được thông suốt. Khắc phục những nhược điểm của loa phường
                                    truyền thống: Thiết lập bản tin phát theo ngày, giờ, tuần; Kiểm soát tình hình hoạt động của toàn bộ hệ thống, chi tiết đến từng thiết bị, từng địa bàn.
                                </p>
                            </div>
                            <!-- /.heading -->
                            <div class="d-flex flex-wrap mb-60">
                                <a href="#" class="btn btn__white mr-30">
                                    <i class="icon-arrow-right"></i>
                                    <span>Tư vấn báo giá</span>
                                </a>
                                <a href="#" class="btn btn__white btn__outlined">Yêu cầu dùng thử</a>
                            </div>
                        </div>
                        <ul class="list-items list-items-layout2 list-items-light list-unstyled">
                            <li>Đã phủ sóng trên 60 Tỉnh /Thành phố </li>
                            <li>Không tiếng ù rè, không bị tiếng lúc to lúc nhỏ</li>
                            <li>Thay thế phát thanh viên bằng công nghệ Text-to-Speech</li>
                        </ul>
                    </div>
                    <!-- /.col-xl-6 -->
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-7">
                        <div class="contact-panel">
                            <form class="contact-panel__form" method="post" action="assets/php/contact.php" id="contactForm">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h4 class="contact-panel__title">Yêu cầu tư vấn báo giá</h4>
                                        <p class="contact-panel__desc mb-20">Bạn cần đội ngũ chuyên viên tư vấn và báo giá về sản phẩm dịch vụ?</p>
                                    </div>
                                    <div class="col-sm-6 col-md-6 col-lg-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Tên" id="contact-name" name="contact-name" required>
                                        </div>
                                    </div>
                                    <!-- /.col-lg-6 -->
                                    <div class="col-sm-6 col-md-6 col-lg-6">
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Email" id="contact-email" name="contact-email" required>
                                        </div>
                                    </div>
                                    <!-- /.col-lg-6 -->
                                    <div class="col-sm-6 col-md-6 col-lg-6">
                                        <div class="form-group">
                                            <select class="form-control">
                                        <option value="1">Giải pháp IP Radio</option>
                                        <option value="2">Ứng dụng dân cư</option>
                                    </select>
                                        </div>
                                    </div>
                                    <!-- /.col-lg-6 -->
                                    <div class="col-sm-6 col-md-6 col-lg-6">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Điện thoại" id="contact-Phone" name="contact-phone" required>
                                        </div>
                                    </div>
                                    <!-- /.col-lg-6 -->
                                    <div class="col-12">
                                        <div class="form-group">
                                            <textarea class="form-control" placeholder="Mô tả yêu cầu" id="contact-message" name="contact-message"></textarea>
                                        </div>
                                        <button type="submit" class="btn btn__primary btn__block btn__xhight mt-10">
                                        <span>Gửi yêu cầu</span> <i class="icon-arrow-right"></i>
                                        </button>
                                        <div class="contact-result"></div>
                                    </div>
                                    <!-- /.col-lg-12 -->
                                </div>
                                <!-- /.row -->
                            </form>
                        </div>
                    </div>
                    <!-- /.col-xl-6 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.Banner layout 1 -->

        <!-- ======================
      Blog Grid
    ========================= -->
        <section class="blog-grid pb-50">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-6 offset-lg-3">
                        <div class="heading text-center mb-40">
                            <h2 class="heading__subtitle">Tin tức sự kiện</h2>
                            <h3 class="heading__title">Tin mới nhất</h3>
                        </div>
                        <!-- /.heading -->
                    </div>
                    <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <!-- Blog Item #1 -->
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="post-item">
                            <div class="post__img">
                                <a href="blog-single-post.html">
                                    <img src="../module/Homepage/assets/images/blog/grid/1.jpg" alt="blog image">
                                </a>
                            </div>
                            <!-- /.blog-img -->
                            <div class="post__body">
                                <div class="post__meta-cat">
                                    <a href="#">Tin tức</a><a href="#">Sản phẩm</a>
                                </div>
                                <!-- /.blog-meta-cat -->
                                <h4 class="post__title"><a href="#">Truyền thanh thông minh cho chính quyền cơ sở</a>
                                </h4>
                                <div class="post__meta">
                                    <span class="post__meta-date">30/7/2022</span>
                                </div>
                                <p class="post__desc">Outsourcing IT infrastructure is a concept that has been around for a while. Characterized in terms of technicians and engineers, workstations and servers, the idea of outsourcing ...
                                </p>
                                <a href="blog-single-post.html" class="btn btn__secondary btn__link">
                                    <span>Xem thêm</span>
                                    <i class="icon-arrow-right"></i>
                                </a>
                            </div>
                            <!-- /.blog-content -->
                        </div>
                        <!-- /.post-item -->
                    </div>
                    <!-- /.col-lg-4 -->
                    <!-- Blog Item #2 -->
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="post-item">
                            <div class="post__img">
                                <a href="blog-single-post.html">
                                    <img src="../module/Homepage/assets/images/blog/grid/2.jpg" alt="blog image">
                                </a>
                            </div>
                            <!-- /.blog-img -->
                            <div class="post__body">
                                <div class="post__meta-cat">
                                    <a href="#">Tin</a><a href="#">Khuyến mãi</a>
                                </div>
                                <!-- /.blog-meta-cat -->
                                <h4 class="post__title"><a href="#">Khuyến mãi 50% giá bán bộ Smart IP Radio Box</a>
                                </h4>
                                <div class="post__meta">
                                    <span class="post__meta-date">30/7/2022</span>
                                </div>
                                <p class="post__desc">Today’s organizations need a quality bench of leaders to drive business outcomes and satisfy employees, customers and investors who now demand more transparency and accountability...
                                </p>
                                <a href="blog-single-post.html" class="btn btn__secondary btn__link">
                                    <span>Xem thêm</span>
                                    <i class="icon-arrow-right"></i>
                                </a>
                            </div>
                            <!-- /.blog-content -->
                        </div>
                        <!-- /.post-item -->
                    </div>
                    <!-- /.col-lg-4 -->
                    <!-- Blog Item #3 -->
                    <div class="col-sm-12 col-md-6 col-lg-4">
                        <div class="post-item">
                            <div class="post__img">
                                <a href="blog-single-post.html">
                                    <img src="../module/Homepage/assets/images/blog/grid/3.jpg" alt="blog image">
                                </a>
                            </div>
                            <!-- /.blog-img -->
                            <div class="post__body">
                                <div class="post__meta-cat">
                                    <a href="#">Tin tức</a><a href="#">Thị trường</a>
                                </div>
                                <!-- /.blog-meta-cat -->
                                <h4 class="post__title"><a href="#">Truyền thanh thông minh: Giải pháp tuyên truyền công nghệ số</a>
                                </h4>
                                <div class="post__meta">
                                    <span class="post__meta-date">30/8/2022</span>
                                </div>
                                <p class="post__desc">Outsourcing IT infrastructure is a concept that has been around for a while. Characterized in terms of technicians and engineers, workstations and servers, the idea of outsourcing ...
                                </p>
                                <a href="blog-single-post.html" class="btn btn__secondary btn__link">
                                    <span>Xem thêm</span>
                                    <i class="icon-arrow-right"></i>
                                </a>
                            </div>
                            <!-- /.blog-content -->
                        </div>
                        <!-- /.post-item -->
                    </div>
                    <!-- /.col-lg-4 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </section>
        <!-- /.blog Grid -->

        <!-- ========================
        Footer
      ========================== -->
        <footer class="footer bg-secondary">
            <div class="container">
                <div class="footer-top pt-50 pb-30">
                    <div class="row">
                        <div class="col-sm-4 col-md-2 col-lg-4">
                            <img src="../module/Homepage/assets/images/logo/logo-light.png" alt="logo" class="mb-30">
                        </div>
                        <!-- /.col-lg-2 -->
                        <div class="col-sm-8 col-md-4 col-lg-3">
                            <h6 class="footer-top__title">Đăng ký nhận thông tin mới nhất về sản phẩm và ưu đãi!</h6>
                        </div>
                        <!-- /.col-lg-3 -->
                        <div class="col-sm-12 col-md-6 col-lg-5">
                            <form class="footer-form d-flex mb-0">
                                <input type="text" class="form-control mr-20" placeholder="Your Email Address">
                                <button type="submit" class="btn btn__primary btn__primary-style2">
                                <span>Đăng ký</span>
                                <i class="icon-arrow-right"></i>
                                </button>
                            </form>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.footer-top -->
                <div class="footer-primary">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-3 footer-widget footer-widget-about">
                            <div class="footer-widget__content">
                                <div class="contact-info">
                                    <h6 class="footer-widget__title">Cần hỗ trợ nhanh?</h6>
                                    <ul class="contact-list list-unstyled">
                                        <li class="color-gray">Có bất kỳ thắc mắc nào hãy liên lạc với chúng tôi để được trợ giúp.
                                        </li>
                                        <li class="mt-20 mb-20">
                                            <a href="tel:0949849939" class="phone-number">
                                                <i class="icon-phone"></i> <span>0949849939</span>
                                            </a>
                                        </li>
                                        <li class="color-body">Số 61 đường số 28, Cư xá Lữ Gia, Phường 15, Quận 11, Tp.HCM</li>
                                    </ul>
                                </div>
                                <!-- /.contact-info -->
                                <ul class="social-icons list-unstyled mb-0">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-youtube"></i></a></li>
                                </ul>
                                <!-- /.social-icons -->
                            </div>
                            <!-- /.footer-widget__content -->
                        </div>
                        <!-- /.col-xl-2 -->
                        <div class="col-sm-6 col-md-6 col-lg-2 offset-lg-1 footer-widget footer-widget-nav">
                            <h6 class="footer-widget__title">Giới thiệu</h6>
                            <div class="footer-widget__content">
                                <nav>
                                    <ul class="list-unstyled">
                                        <li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Năng lực</a></li>
                                        <li><a href="#">Tin tức</a></li>
                                        <li><a href="#">Pháp lý</a></li>
                                        <li><a href="#">Liên hệ</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- /.footer-widget__content -->
                        </div>
                        <!-- /.col-lg-2 -->
                        <div class="col-sm-6 col-md-6 col-lg-2 footer-widget footer-widget-nav">
                            <h6 class="footer-widget__title">Giải pháp</h6>
                            <div class="footer-widget__content">
                                <nav>
                                    <ul class="list-unstyled">
                                        <li><a href="#">Truyền thanh thông minh</a></li>
                                        <li><a href="#">Truyền thanh cơ sở</a></li>
                                        <li><a href="#">Ứng dụng dân cư</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- /.footer-widget__content -->
                        </div>
                        <!-- /.col-lg-2 -->
                        <div class="col-sm-6 col-md-6 col-lg-2 footer-widget footer-widget-nav">
                            <h6 class="footer-widget__title">Tài liệu</h6>
                            <div class="footer-widget__content">
                                <nav>
                                    <ul class="list-unstyled">
                                        <li><a href="#">Giá tham khải</a></li>
                                        <li><a href="#">Bảo mật</a></li>
                                        <li><a href="#">Câu hỏi thường gặp</a></li>
                                        <li><a href="#">Hướng dẫn SD</a></li>
                                        <li><a href="#">Site map</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!-- /.footer-widget__content -->
                        </div>
                        <!-- /.col-lg-2 -->
                        <div class="col-sm-6 col-md-6 col-lg-2 footer-widget footer-widget-nav">
                            <h6 class="footer-widget__title">Download ứng dụng</h6>
                            <div class="footer-widget__content">
                                <a href="#" class="btn btn__white btn__download mb-20">
                                    <i class="fab fa-apple"></i>
                                    <span>App Store</span>
                                </a>
                                <a href="#" class="btn btn__white btn__download mb-20">
                                    <i class="fab fa-google-play"></i>
                                    <span>Google Play</span>
                                </a>
                            </div>
                            <!-- /.footer-widget__content -->
                        </div>
                        <!-- /.col-lg-2 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.footer-primary -->
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 text-center pb-40">
                        <span class="fz-14">&copy; 2022 SaigonLab . All Rights Reserved </span>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container -->
        </footer>
        <!-- /.Footer -->
        <button id="scrollTopBtn"><i class="fas fa-long-arrow-alt-up"></i></button>

        <div class="login-popup" id="login-popup">
            <div class="login-popup-wrapper">
                <form class="login-popup__form">
                    <h3 class="login-popup__title">Login!</h3>
                    <p class="login-popup__desc">Connect, organize and get things done to keep your IT business safe.</p>
                    <div class="form-group mb-20">
                        <i class="icon-mail input-icon"></i>
                        <input type="text" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group mb-20">
                        <i class="icon-lock input-icon"></i>
                        <input type="password" class="form-control" placeholder="********">
                    </div>
                    <div class="d-flex align-items-center justify-content-between mb-20">
                        <div class="custom-control custom-checkbox d-flex align-items-center">
                            <input type="checkbox" class="custom-control-input" id="customCheck1">
                            <label class="custom-control-label" for="customCheck1">Remember Me!</label>
                        </div>
                        <a href="#" class="fz-14 font-weight-bold color-secondary">Forget Password?</a>
                    </div>
                    <button type="submit" class="btn btn__primary btn__block btn__xl">
            <span>Login</span>
            <i class="icon-arrow-right"></i>
          </button>
                </form>
                <div class="d-flex justify-content-center align-items-center mt-20">
                    <span class="color-white fz-14 font-weight-bold">Don’t Have An Account?</span>
                    <button id="go-register" class="go-register fz-14 font-weight-bold">
            <span>Register Here</span><i class="icon-arrow-right"></i>
          </button>
                </div>
            </div>
        </div>
        <!-- /.login-popup -->

        <div class="login-popup" id="register-popup">
            <div class="login-popup-wrapper">
                <form class="login-popup__form">
                    <h3 class="login-popup__title">Register!</h3>
                    <p class="login-popup__desc">Connect, organize and get things done to keep your IT business safe.</p>
                    <div class="form-group mb-20">
                        <i class="icon-mail input-icon"></i>
                        <input type="text" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group mb-20">
                        <i class="icon-lock input-icon"></i>
                        <input type="password" class="form-control" placeholder="********">
                    </div>
                    <div class="d-flex align-items-center justify-content-between mb-20">
                        <div class="custom-control custom-checkbox d-flex align-items-center">
                            <input type="checkbox" class="custom-control-input" id="customCheck2">
                            <label class="custom-control-label" for="customCheck2">I read & agree to <a href="#">Terms &
                  Conditions</a></label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn__primary btn__block btn__xl">
            <span>Register</span>
            <i class="icon-arrow-right"></i>
          </button>
                </form>
                <div class="d-flex justify-content-center align-items-center mt-20">
                    <span class="color-white fz-14 font-weight-bold">Have An Account?</span>
                    <button id="go-login" class="go-login fz-14 font-weight-bold">
            <span>Login Here</span><i class="icon-arrow-right"></i>
          </button>
                </div>
            </div>
        </div>
        <!-- /.login-popup -->

        <div class="search-popup">
            <button type="button" class="search-popup__close"><i class="fas fa-times"></i></button>
            <form class="search-popup__form">
                <input type="text" class="search-popup__form__input" placeholder="Type Words Then Enter">
                <button class="search-popup__btn"><i class="icon-search"></i></button>
            </form>
        </div>
        <!-- /. search-popup -->
    </div>
    <!-- /.wrapper -->

    <script src="../module/Homepage/assets/js/jquery-3.5.1.min.js"></script>
    <script src="../module/Homepage/assets/js/plugins.js"></script>
    <script src="../module/Homepage/assets/js/main.js"></script>
</body>

</html>