 <!-- <?php
                    foreach ($list as $p) {
                        echo "<tr>";
                        echo "<td>{$p->getPost_id()}</td>";
                        echo "<td>{$p->getTitle()}</td>";
                        echo "<td>{$p->getContent()}</td>";
                        echo "<td>{$p->getCreate_user()}</td>";
                        echo "<td>{$p->getApprove_user()}</td>";
                        echo "<td>{$p->getCreate_date()}</td>";
                        echo "<td>{$p->getModify_date()}</td>";
                        echo "<td>{$p->getApprove_date()}</td>";
                        echo "<td>{$p->getStatus()}</td>";
                        echo "<td>{$p->getSubnews_id()}</td>";
                        echo "<td><input name='delete' type='button' value='delete'></td>";
                        echo "</tr>";
                    }
                    ?> -->